[phases.setup]
nixPkgs = ["openjdk17", "maven"]

[phases.build]
cmds = ["chmod +x mvnw", "./mvnw clean package -DskipTests"]

[start]
cmd = "java -jar target/*.jar"
[phases.cleanup]
cmds = ["rm -rf target"]
