# Etapa 1: Construcción con Maven + Java
FROM maven:3.9.3-eclipse-temurin-17 AS build

WORKDIR /app
COPY tfg /app
RUN mvn clean package -DskipTests

# Etapa 2: Solo Java para ejecutar
FROM eclipse-temurin:17-jdk
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "app.jar"]
