[build]
builder = "NIXPACKS"

[phases.setup]
nixPkgs = ["openjdk17"]

[phases.install]
cmds = [
    "cd tfg && chmod +x mvnw"
]

[phases.build]
cmds = [
    "cd tfg && ./mvnw clean install -DskipTests"
]

[start]
cmd = "java -jar tfg/target/*.jar"
